# Generated by Django 3.0.3 on 2020-03-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spacex',
            new_name='SpacexItem',
        ),
    ]
